- name: Get all devices from Nautobot
  uri:
   url: "http://10.10.10.104:8080/api/dcim/devices/"
   method: GET
   return_content: yes
    headers:
      Authorization: "Token 3a28f76fe9d03a5467e955e71cc5b37c6a047b18"
      Accept: "application/json; indent=4"
    return_content: yes
  register: nautobot_response

- name: Check for backup_enable attribute in devices
  debug:
    msg: "Device {{ item.name }} has backup_state: true"
  loop: "{{ nautobot_response.json.results }}"
  when: item.custom_fields.backup_state == true

