---
- name: Get devices from Nautobot
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get all devices from Nautobot
      uri:
        url: "http://10.10.10.104:8080/api/dcim/devices/"
        method: GET
        return_content: yes
        headers:
          Authorization: "Token 3a28f76fe9d03a5467e955e71cc5b37c6a047b18"
          Accept: "application/json; indent=4"
        return_content: yes
      register: nautobot_response

        #    - name: Show Nautobot API response
        #debug:
        #var: nautobot_response.json

    - name: Print message if backup is enabled
      debug:
        msg: "Backup is enabled on {{ item.name }}"
      when: item.custom_fields is defined and item.custom_fields.backup_state | default(false) | bool
      loop: "{{ response.json.results }}"
